# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CTProjectCategory' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod "CTMediator"

  # Pods for CTProjectCategory

  target 'CTProjectCategoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CTProjectCategoryUITests' do
    # Pods for testing
  end

end
